export const subRoutes = {
  "/sources/all-sources": {
    id: "all",
    label: "All Sources",
    parent: "/sources",
    count: 123,
  },
  "/sources/machines": {
    id: "machines",
    label: "Machines",
    parent: "/sources",
    count: 2,
  },
  "/sources/machines-without-plan": {
    id: "no-plan",
    label: "Machines without Plan",
    parent: "/sources",
    count: 30,
  },
  "/sources/agentless-vms": {
    id: "agentless",
    label: "Agentless VMs",
    parent: "/sources",
    count: 60,
  },
  "/sources/unc-nfs-paths": {
    id: "unc",
    label: "UNC/NFS Paths",
    parent: "/sources",
    count: 8,
  },
  "/destinations/recovery-point-servers": {
    id: "rps",
    label: "Recovery Point Servers",
    parent: "/destinations",
    count: 21,
  },
  "/destinations/data-stores": {
    id: "datastores",
    label: "Data Stores",
    parent: "/destinations",
    count: 21,
  },
  "/destinations/arcserve-cyber-resilient-storage-accounts": {
    id: "acrsaccounts",
    label: "Arcserve Cyber Resilient Storage Accounts",
    parent: "/destinations",
    count: 21,
  },
  "/destinations/shared-folders": {
    id: "share-folders",
    label: "Shared Folders",
    parent: "/destinations",
    count: 21,
  },
  "/infrastructures/hypervisors": {
    id: "hypervisors",
    label: "Hypervisors",
    parent: "/infrastructures",
    count: 22,
  },
  "/infrastructures/sites": {
    id: "sites",
    label: "Sites",
    parent: "/infrastructures",
    count: 11,
  },
  "/infrastructures/storage-arrays": {
    id: "storage-arrays",
    label: "Storage Arrays",
    parent: "/infrastructures",
    count: 2,
  },
  "/infrastructures/proxies": {
    id: "proxies",
    label: "Proxies",
    parent: "/infrastructures",
    count: 5,
  },
  "/infrastructures/oracle-hosts": {
    id: "oracle-hosts",
    label: "Oracle Hosts",
    parent: "/infrastructures",
    count: 5,
  },
  "/infrastructures/cloud-accounts": {
    id: "cloud-accounts",
    label: "Cloud Accounts",
    parent: "/infrastructures",
    count: 5,
  },
  "/infrastructures/cloud-protection-orchestrators": {
    id: "cloud-protection-orchestrators",
    label: "Cloud Protection Orchestrators",
    parent: "/infrastructures",
    count: 5,
  },
  "/disaster-recovery/dr-runbooks": {
    id: "dr-runbooks",
    label: "DR Runbooks",
    parent: "/disaster-recovery",
    count: 18,
  },
  "/disaster-recovery/instant-vms": {
    id: "instant-vms",
    label: "Instant VMs",
    parent: "/disaster-recovery",
    count: 18,
  },
  "/disaster-recovery/mounted-recovery-points": {
    id: "mounted-recovery-points",
    label: "Mounted Recovery Points",
    parent: "/disaster-recovery",
    count: 18,
  },
  "/disaster-recovery/virtual-standby": {
    id: "virtual-standby",
    label: "Virtual Standby",
    parent: "/disaster-recovery",
    count: 18,
  },
  "/disaster-recovery/dr-runbooks/new": {
    id: "dr-runbook-new",
    label: "Add DR Runbook",
    parent: "/disaster-recovery/dr-runbooks",
  },
  "/plans/all-plans": {
    id: "all-plans",
    label: "All Plans",
    parent: "/plans",
    count: 5,
  },
  "/plans/agent-based-windows-backups": {
    id: "agent-based-windows-backups",
    label: "Agent-based Windows Backups",
    parent: "/plans",
    count: 5,
  },
  "/plans/agent-based-linux-backups": {
    id: "agent-based-linux-backups",
    label: "Agent-based Linux Backups",
    parent: "/plans",
    count: 5,
  },
  "/plans/agent-based-backups-to-ac-for-disaster-recovery": {
    id: "agent-based-backups-to-ac-for-disaster-recovery",
    label: "Agent-based Backups to AC for Disaster Recovery",
    parent: "/plans",
    count: 5,
  },
  "/plans/agent-based-backups-directly-to-arserve-cloud": {
    id: "agent-based-backups-directly-to-arserve-cloud",
    label: "Agent-based Backups Directly to Arserve Cloud",
    parent: "/plans",
    count: 5,
  },
  "/plans/agentless-backups": {
    id: "agentless-backups",
    label: "Agentless Backups",
    parent: "/plans",
    count: 5,
  },
  "/plans/copy-from-remotely-managed-rps": {
    id: "copy-from-remotely-managed-rps",
    label: "Copy From Remotely-managed RPS",
    parent: "/plans",
    count: 5,
  },
  "/plans/oracle-database-backups": {
    id: "oracle-database-backups",
    label: "Oracle Database Backups",
    parent: "/plans",
    count: 5,
  },
  "/plans/uncnfs-backups": {
    id: "uncnfs-backups",
    label: "UNC/NFS Backups",
    parent: "/plans",
    count: 5,
  },
  "/reports/backup-jobs": {
    id: "backup-jobs",
    label: "Backup Jobs",
    parent: "/reports",
    count: 5,
  },
  "/reports/data-transfer": {
    id: "data-transfer",
    label: "Data Transfer",
    parent: "/reports",
    count: 5,
  },
  "/reports/managed-report-schedules": {
    id: "managed-report-schedules",
    label: "Managed Report Schedules",
    parent: "/reports",
    count: 5,
  },
  "/reports/recovery-point": {
    id: "recovery-point",
    label: "Recovery Point",
    parent: "/reports",
    count: 5,
  },
  "/reports/source-protection": {
    id: "source-protection",
    label: "Source Protection",
    parent: "/reports",
    count: 5,
  },
  "/reports/stored-data": {
    id: "stored-data",
    label: "Stored Data",
    parent: "/reports",
    count: 5,
  },
  "/settings/source-groups": {
    id: "source-groups",
    label: "Source Groups",
    parent: "/settings",
    count: 5,
  },
  "/settings/roles": {
    id: "roles",
    label: "Roles",
    parent: "/settings",
    count: 5,
  },
  "/settings/entitlements": {
    id: "entitlements",
    label: "Entitlements",
    parent: "/settings",
    count: 5,
  },
  "/settings/branding": {
    id: "branding",
    label: "Branding",
    parent: "/settings",
    count: 5,
  },
  "/settings/source-discovery-configuration": {
    id: "source-discovery-configuration",
    label: "Source Discovery Configuration",
    parent: "/settings",
    count: 5,
  },
  "/settings/default-deployment-settings": {
    id: "default-deployment-settings",
    label: "Default Deployment Settings",
    parent: "/settings",
    count: 5,
  },
  "/settings/approval-workflows": {
    id: "approval-workflows",
    label: "Approval Workflows",
    parent: "/settings",
    count: 5,
  },
};
